services:
  laravel-docker:
    container_name: example_app
    build: .
    volumes:
      - ./:/var/www/html
    ports:
      - 9010:80

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_example_app
    ports:
    - 3310:3306

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9910:80
    environment:
      - PMA_ARBITRARY=1
